# Write Kubernetes Deployment Script

# Kubernetes Deployment API version
apiVersion: apps/v1
# Declares the kind of resource as a Deployment
kind: Deployment
# Metadata section provides details such as the name of the deployment
metadata:
  name: book-catalog
 # Specification for the deployment
spec:
  replicas: 1 # Defines the number of pod replicas to run, here it's set to 1
  selector:
    matchLabels:
      app: book-catalog #the label selector
  template:
    metadata:
      labels:
        app: book-catalog # The label assigned to the pod
     # Defines the container inside the pod
    spec:
      containers: 
      - name: video-streaming  # Name of the container
        image: week08:1 #docker image tag
        ports:
        - containerPort: 8000 # Exposes container's port 8000
        imagePullPolicy: Never # Tells Kubernetes not to pull the image
        env:  # Environment variables for the container
        - name: DATABASE_URL
          value: "postgresql://week08_ltts_user:KrK8pAFGxLiF1K75ZdxtDhA78vfvr9xc@dpg-crh46t08fa8c738rvde0-a.oregon-postgres.render.com/week08_ltts"
---
# Declares a Kubernetes Service, which exposes the app to the network
apiVersion: v1
kind: Service
metadata:
  name: book-catalog # The name of the service is 'book-catalog'

# Service specification
spec:
  selector:
    app: book-catalog # The service targets pods with this label
  type: NodePort  # Type of service
  ports:
    - protocol: TCP # The protocol used by the service
      port: 8000  # The port on which the service is exposed to the outside world
      targetPort: 8000 # The port on the container that the service routes traffic to
      